apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-f
  name: app-f
spec:
  containers:
  - image: machine424/app-f
    name: app-f
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
