apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
nodeRegistration:
token: "yxddj3.7zcqr0inoe4v59qp"
discoveryTokenUnsafeSkipCAVerification: true
discoveryTokenAPIServers:
  - 52.208.65.99:6443
